// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emktqltshiumxdpaxpfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVta3RxbHRzaGl1bXhkcGF4cGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDM0NTEsImV4cCI6MjA3MjExOTQ1MX0.su34-9V8RdLaTBp9njeFahUkAKI0NH7U8ssTuVNhUtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});